baseURL = 'https://pwnxr.github.io/'
buildDrafts = true
buildFuture = true
languageCode = 'en-us'
theme = "nightfall"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
pagerSize = 3

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
user = "pwnxr"
hostname = "github.io"

# You can configure external links to open in new tabs by adding this parameter
openLinksInNewTab = true

displayDateFormat = "2006-01-02"

# Global metadata display settings
# Each can be overridden in individual post frontmatter
showMetadata = true       # Master switch for all metadata display
showPublishedDate = true  # Show published date on post page
showReadingTime = true    # Show reading time on post page
showTags = true           # Show tags on post page
showAuthors = true        # Show authors on post page
showCategories = true     # Show categories on post page

  [params.author]
    name = "Abdullah Waleed"  # Website and RSS feed author
    email = "abdallatheco0oder@gmail.com"  # RSS feed email address

[[params.social]]
key = 0
name = "github"
url = "https://github.com/pwnxr"
target = "_blank"
aria = "GitHub Profile"

[[params.social]]
key = 1
name = "twitter"
url = "https://x.com/idevenk01"
aria = "Twitter Profile"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.linkedin.com/in/pwnxr/"
aria = "LinkedIn Profile"

[[params.social]]
key = 3
name = "email"
url = "mailto:abdallatheco0oder@gmail.com"
aria = "My e-Mail Address"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10
